sudo: required
dist: xenial
language: node_js
node_js:
  - '7.10'

branches:
  only:
    - master

before_script:
# - npm install -g firebase-tools
- npm install -g @angular/cli
- npm install -g angular-cli-ghpages

script:
- ng build --prod --base-href="https://finnzeit.github.io/ng-instant/"

after_success:
# - firebase deploy --token $FIREBASE_TOKEN
- ngh --repo=https://$GH_TOKEN@github.com/finnzeit/ng-instant.git --name="finnzeit" --email=finnzeit@gmail.com

notifications:
  email:
    on_failure: change
    on_success: change
