version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    
    working_directory: ~/instant

    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: sudo npm install -g @angular/cli
      - run: sudo npm install -g angular-cli-ghpages
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  
  deploy:
    machine:
      enabled: true

    steps:
     - run: ng build --prod --base-href "https://zeit.js.org/instant/"
     - run: ngh --repo=https://GH_TOKEN@github.com/finnzeit/instant.git --name="finnzeit" --email=finnzeit@gmail.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
    